# This workflow warns and then closes issues that may be ignoring our template.
#
# You can adjust the behavior by modifying this file.
name: Close issues

on:
  issues:
    types: [opened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check if title contains keyword
      if: contains(github.event.issue.title, '[Bug report]') == false &&
        contains(github.event.issue.title, '[Feature request]') == false
      uses: peter-evans/close-issue@v3
      with:
          labels: |
            why are you ignoring the template
